name: Auto Scraper
on:
  push:
    branches: [ main ]
  workflow_dispatch: 

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      - name: 1. 下载代码
        uses: actions/checkout@v4

      - name: 2. 安装 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 3. 安装必要的工具
        run: pip install requests

      - name: 4. 执行爬虫脚本 (Run Scraper)
        env:
          MY_PROXY_URL: ${{ secrets.PROXY_URL }}
        run: |
          python scraper.py

      - name: 5. 打包生成物
        uses: actions/upload-pages-artifact@v3
        with:
          path: '.'

      - name: 6. 发布到网页
        uses: actions/deploy-pages@v4
